### PR TITLE
Added My Project (BMI Calculator)

### PR DESCRIPTION
**Pull request by imobasshir**
Added BMI calculator app

### CODE REVIEW

**Comment by imobasshir** [comment]
I have added my project can you please see it and merge it by adding hacktoberfest label

**Comment by Tamanna-S** [comment]
may you please rename your folder with your github username and project name separated with '-'.

**Comment by imobasshir** [comment]
I have done the required changes

**Comment by Tamanna-S** [comment]
amazing!!🌟

**Pull request merged**
