### PR TITLE
add cheems language convertor

### PR DESCRIPTION
**Pull request by nithin-gith**

### CODE REVIEW

**Comment by Tamanna-S** [comment]
this repo is for vanilla js

**Comment by nithin-gith** [comment]
Hey, I have actually removed the attendance tracker and added cheems lang converter which is vanilla js 
please have a loot at it

**Comment by Tamanna-S** [comment]
okay, may you make a new pr with that project only.

**Comment by nithin-gith** [comment]
Made a PR now

**Pull request closed without merging**
