### PR TITLE
basic javascript calculator

### PR DESCRIPTION
**Pull request by arpitjha867**
Added a calculator made with vanilla Js

### CODE REVIEW

**Comment by Tamanna-S** [comment]
amazing! but may you please read the contribution.md and do some changes like add readme..

**Comment by arpitjha867** [comment]
added the readme with info and video preview

**Comment by arpitjha867** [comment]
> amazing! but may you please read the contribution.md and do some changes like add readme..

Hi Tamanna I have made the necessay changes please take a look and merge the request.

**Comment by Tamanna-S** [comment]
awesome!!🔥

**Pull request merged**
