### PR TITLE
 Javascript - YouTube Videos Playlist Queue Player 

### PR DESCRIPTION
**Pull request by codersalman**
@Tamanna-S  Review it

### CODE REVIEW

**Comment by Tamanna-S** [comment]
add readme with ss or short video

**Comment by codersalman** [comment]
@Tamanna-S  Added Readme and Screenshot

**Comment by codersalman** [comment]
Any Update ?

**Comment by Tamanna-S** [comment]
may you add a short video as the ss is not enough to show what your project is doing.

**Comment by codersalman** [comment]
What about demo link ?

**Comment by Tamanna-S** [comment]
would be great.

**Comment by codersalman** [comment]
https://youtube-videos-playlist-queue-player-using-javascript.pages.dev/

**Comment by codersalman** [comment]
with this project you can add random videos and play them in a playlist as well as you can add timeline in it

**Review by alicalimli — COMMENTED** [review]
Nice!

**Pull request merged**
