### PR TITLE
Added drum kit project.

### PR DESCRIPTION
**Pull request by Mohit-Aasirwal**
This project is made with DOM manipulation in vanilla JS. Kindly merge this PR with issuing label of hacktoberfest.
Thanks for giving opportunity.

### CODE REVIEW

**Comment by Tamanna-S** [comment]
great but read contribution guide and make changes accordingly

**Comment by Mohit-Aasirwal** [comment]
Ok, I've done the changes suggested by you in contributing.md
Now, please merge this repository.
thanks for providing opportunity.
kindly label the PR first

**Comment by Tamanna-S** [comment]
make the changes otherwise i will not merge it

**Comment by Mohit-Aasirwal** [comment]
> make the changes otherwise i will not merge it

what kind of changes are you proposing. I am unable to get them.
I've done reading contributing.md and wish to know about what further changes can I do for merging this PR.
Also if there is any error in code please mention.

**Comment by Tamanna-S** [comment]
put your project in basic-projects rename your folder with your github username and project name use '-' not spaces  add a readme in your project and add a short video if possible

**Pull request closed without merging**
