### PR TITLE
SNAKE GAME CONTRIBUTED

### PR DESCRIPTION
**Pull request by PAVANNANI007**

### CODE REVIEW

**Comment by Tamanna-S** [comment]
hey @PAVANNANI007  amazing project but may you add the readme.

**Comment by PAVANNANI007** [comment]
Okay I will tamanna

**Comment by PAVANNANI007** [comment]
i have already deployed it thats why there is github file in that

**Comment by PAVANNANI007** [comment]
done tamanna can you please merge it now

**Comment by Tamanna-S** [comment]
i can't merge it like this, i don't know what are you doing with firebase functions and these json files, some files are repeating also.

**Comment by Tamanna-S** [comment]
hey make a new pr for the same this is very mess

**Pull request closed without merging**
