### PR TITLE
Add rock-paper-scissors game

### PR DESCRIPTION
**Pull request by virejdasani**

### CODE REVIEW

**Comment by Tamanna-S** [comment]
very nice but may you please read the contributing.md and as there's a bot in you program so this will be an intermediate project make a floder named intermediate-projects and add your project in that!

**Comment by virejdasani** [comment]
Sure, I'll do that

**Comment by virejdasani** [comment]
Done, let me know if you need anything else :)

**Comment by Tamanna-S** [comment]
just 2 things, add a readme in your project and rename your floder with virejdasani-rock-paper-scissors as stated in contributing.md

**Comment by virejdasani** [comment]
Done!

**Comment by Tamanna-S** [comment]
awesome!

**Pull request merged**
