### PR TITLE
create project background clolor flipper

### PR DESCRIPTION
**Pull request by jainpatel25**
this is my first project in javascript

### CODE REVIEW

**Comment by jainpatel25** [comment]
can you please add a hactoberfest tag?

**Review by alicalimli — APPROVED** [review]
Great job!

**Comment by jainpatel25** [comment]
Hey can u please add a hactoberfest tag?

**Comment by theDreamer911** [comment]
you will get the tag automatically after your pull request merged by the owner

**Comment by Tamanna-S** [comment]
good one @jainpatel25

**Pull request merged**
