### PR TITLE
Real time weather Forcasting Application

### PR DESCRIPTION
**Pull request by Shivam10025**

### CODE REVIEW

**Comment by Tamanna-S** [comment]
read the contribution guide and put your project in the respective folder!

**Comment by Shivam10025** [comment]
I have done the changes thanks for your help

**Comment by Tamanna-S** [comment]
it should go in advance as its using apis stuff

**Comment by Shivam10025** [comment]
ohh sorry for that I miss read's the thing readme, again thanks

**Comment by Tamanna-S** [comment]
you should read that always and again just a single thing rename your folder with your github username and project name separated with '-'

**Comment by Tamanna-S** [comment]
than i will merge it

**Pull request merged**
